/** Stable public facade for schema-generated wire identifier aliases. */

export type {
  AgentId,
  ApprovalId,
  ArtifactId,
  AutomationBindingId,
  BranchId,
  ChangeSetId,
  CheckpointId,
  ClientId,
  CodeNodeId,
  CommandId,
  CorrelationId,
  CouncilResultId,
  DaemonInstanceId,
  DocumentId,
  JsonValue,
  InboxEntryId,
  LearningId,
  MemoryId,
  MessageId,
  ModelId,
  OrganizationId,
  PluginId,
  PromptId,
  QuestionId,
  RegistryItemId,
  RepositoryId,
  RunId,
  SessionId,
  SkillId,
  TaskId,
  Timestamp,
  ToolId,
  UserId,
  WorkflowId,
  WorkspaceId,
} from "./generated/ids.js";

/** UUIDv7 strings on the wire (serde `transparent` newtypes over `Uuid`). */
export type Uuid = string;
