#!/usr/bin/env python3
"""CI check: every `<!-- doc-count:… -->` marker in the docs still matches
reality. THE actual fix for the "docs claim a number that's been stale for
months" class of bug — every prior fix to one of these numbers rots again the
next time someone adds or removes a test, a model row or a crate, unless
something re-checks it on every PR. This is that something.

## What a marker looks like

Three kinds, all one line, placed immediately next to the prose sentence they
back (see `ROADMAP.md` for live examples of each):

    <!-- doc-count:test sources="crates/sandbox/src" expect=155 label="sandbox unit tests" -->
    <!-- doc-count:match sources="crates/providers/builtin_catalog.toml" pattern="^\\[\\[model\\]\\]$" expect=386 label="curated model rows" -->
    <!-- doc-count:vitest project="extensions/vscode" metric="tests" expect=217 label="VS Code vitest suite" -->

- **`test`** counts `#[test]` / `#[tokio::test]` attributes. `sources` is a
  comma-separated list of paths, each a directory (walked for `*.rs`) or a
  single file, relative to the repo root.
- **`match`** counts regex matches (`re.MULTILINE`) over the same kind of
  `sources` list, with an optional `glob="*.toml"` for directories (default
  `*`). This is the general counter: catalog rows, enum variants, corpus files,
  workspace members — anything a regex can count exactly.
- **`vitest`** compares against a REAL vitest run, because no regex can count a
  JavaScript suite honestly: `extensions/vscode` declares 105 `it(`/`test(`
  blocks and vitest reports **217** tests, since `.each` tables expand at run
  time. `metric` is `tests` or `files`. It needs `--vitest-report
  <project>=<path>` pointing at the JSON reporter's output (`vitest run
  --reporter=json --outputFile=…`), so it runs in the `extension` CI job that
  already has Node; the cheap `doc-counts` job passes `--skip-vitest`, which
  prints exactly which markers were deferred rather than skipping silently.

## The prose is checked too

A number in a marker that disagrees with the number in the sentence above it is
the same bug one layer down, and it happened here: `ROADMAP.md` said "154 unit
tests" one line above `expect=155`, and the gate was green because it only read
the marker. So every marker's `expect` must also appear as a number in the
prose lines immediately around it (`--no-prose-check` opts out for a marker
whose prose deliberately carries no digit, e.g. "grows with every outcome").

## Methodology — and its one deliberate limitation

`test` and `match` counts are static regexes over the file text — NOT `cargo
test --list`, which would need a build. This is a deliberate trade-off: the
whole point is that this check runs on EVERY PR cheaply enough that nobody
skips it. It cannot see doc-tests, tests behind a non-default feature, or a
test generated by a macro that doesn't literally spell `#[test]`. If a future
marker's source uses one, prefer fixing the count at its source over silencing
this check.

## Usage

    check_doc_test_counts.py [--roots PATH ...] [--skip-vitest]
                             [--vitest-report PROJECT=PATH ...]

Exits 1 and prints every mismatch (not just the first) if any marker's `expect`
no longer matches. Exits 0, printing a summary, when every marker holds. Exits
2 on a malformed marker or an unreadable source path — a broken CHECK is a bug
in the marker, not a silent skip.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

MARKER_RE = re.compile(r"<!--\s*doc-count:(?P<kind>[a-z]+)\s+(?P<attrs>.*?)-->")
# A quoted value may contain an escaped quote (`pattern="^\"crates/…\",?$"`),
# so the value is not simply "everything up to the next quote".
ATTR_RE = re.compile(r'(?P<key>[a-z_]+)=(?:"(?P<qval>(?:[^"\\]|\\.)*)"|(?P<bval>[^\s"]+))')
TEST_ATTR_RE = re.compile(r"#\[(?:tokio::)?test\]")

DEFAULT_ROOTS = [
    "ROADMAP.md",
    "README.md",
    "docs/README.md",
    "docs/cli-and-tui-user-guide.md",
    "evals/README.md",
]

KNOWN_KINDS = ("test", "match", "vitest")
#: How many prose lines either side of a marker are searched for its number.
PROSE_WINDOW = 3


def fail(message: str) -> "SystemExit":
    return SystemExit(f"error: {message}")


def parse_attrs(kind: str, attrs: str, where: str) -> dict[str, str]:
    parsed = {
        m.group("key"): (
            m.group("qval").replace('\\"', '"') if m.group("qval") is not None else m.group("bval")
        )
        for m in ATTR_RE.finditer(attrs)
    }
    if "expect" not in parsed or not parsed["expect"].isdigit():
        raise fail(f"{where}: doc-count:{kind} marker has no numeric `expect=`")
    if kind == "vitest":
        required = ("project", "metric")
    else:
        required = ("sources",)
    for key in required:
        if key not in parsed:
            raise fail(f"{where}: doc-count:{kind} marker is missing `{key}=`")
    if kind == "match" and "pattern" not in parsed:
        raise fail(f"{where}: doc-count:match marker is missing `pattern=`")
    if kind == "vitest" and parsed["metric"] not in ("tests", "files"):
        raise fail(f"{where}: doc-count:vitest `metric` must be `tests` or `files`")
    return parsed


def source_files(repo_root: Path, source: str, glob: str, where: str) -> list[Path]:
    path = repo_root / source
    if path.is_dir():
        return sorted(path.rglob(glob))
    if path.is_file():
        return [path]
    raise fail(f"{where}: doc-count source does not exist: {source} (resolved {path})")


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as error:
        raise fail(f"could not read source {path}: {error}")


def count_over_sources(repo_root: Path, attrs: dict[str, str], regex: re.Pattern, glob: str, where: str) -> int:
    total = 0
    for source in (s.strip() for s in attrs["sources"].split(",") if s.strip()):
        for path in source_files(repo_root, source, glob, where):
            total += len(regex.findall(read_text(path)))
    return total


def vitest_count(reports: dict[str, Path], attrs: dict[str, str], where: str) -> int:
    project = attrs["project"]
    path = reports[project]
    try:
        with open(path, "r", encoding="utf-8") as f:
            report = json.load(f)
    except (OSError, json.JSONDecodeError) as error:
        raise fail(f"{where}: could not read vitest report {path}: {error}")
    if attrs["metric"] == "tests":
        value = report.get("numTotalTests")
    else:
        value = len(report.get("testResults") or [])
    if value is None:
        raise fail(f"{where}: vitest report {path} has no `numTotalTests`")
    # A red suite must never be read as a count: 0 failures is part of the claim.
    if report.get("numFailedTests"):
        raise fail(
            f"{where}: vitest report {path} records {report['numFailedTests']} failing test(s) — "
            "fix the suite before comparing counts"
        )
    return int(value)


def prose_holds(lines: list[str], marker_line: int, expect: int) -> bool:
    """Whether `expect` appears as a number in the prose around the marker.

    Both directions and a small window, because a marker sometimes splits its
    own sentence (`ROADMAP.md`: "579 TUI" / marker / "tests green"). Commas are
    stripped so "2,771" matches 2771."""
    lo = max(0, marker_line - PROSE_WINDOW)
    hi = min(len(lines), marker_line + PROSE_WINDOW + 1)
    window = " ".join(
        line for i, line in enumerate(lines[lo:hi], start=lo)
        if "doc-count:" not in line
    ).replace(",", "")
    return re.search(rf"(?<![\d.]){expect}(?![\d.])", window) is not None


def check_doc(
    repo_root: Path,
    doc_path: Path,
    vitest_reports: dict[str, Path],
    skip_vitest: bool,
    prose_check: bool,
) -> tuple[list[str], int, list[str]]:
    """Returns `(failures, markers_checked, deferred_labels)`."""
    text = read_text(doc_path)
    lines = text.splitlines()
    failures: list[str] = []
    deferred: list[str] = []
    checked = 0

    for match in MARKER_RE.finditer(text):
        kind = match.group("kind")
        line_no = text.count("\n", 0, match.start()) + 1
        where = f"{doc_path}:{line_no}"
        if kind not in KNOWN_KINDS:
            raise fail(f"{where}: unknown marker kind doc-count:{kind} (known: {', '.join(KNOWN_KINDS)})")
        attrs = parse_attrs(kind, match.group("attrs"), where)
        expect = int(attrs["expect"])
        label = attrs.get("label") or "(unlabeled)"

        if kind == "vitest" and attrs["project"] not in vitest_reports:
            if skip_vitest:
                deferred.append(f"{where}: {label!r}")
                continue
            raise fail(
                f"{where}: doc-count:vitest needs --vitest-report {attrs['project']}=<path> "
                "(run `vitest run --reporter=json --outputFile=…` first), or pass --skip-vitest "
                "to defer it to the job that can run it"
            )

        if kind == "test":
            actual = count_over_sources(repo_root, attrs, TEST_ATTR_RE, "*.rs", where)
            unit = "test(s)"
        elif kind == "match":
            try:
                regex = re.compile(attrs["pattern"], re.MULTILINE)
            except re.error as error:
                raise fail(f"{where}: doc-count:match pattern is not a valid regex: {error}")
            actual = count_over_sources(repo_root, attrs, regex, attrs.get("glob", "*"), where)
            unit = "match(es)"
        else:
            actual = vitest_count(vitest_reports, attrs, where)
            unit = f"vitest {attrs['metric']}"

        checked += 1
        if actual != expect:
            failures.append(
                f"{where}: {label!r} claims {expect} {unit}, but {actual} are actually there "
                f"now. Fix the prose AND the marker's `expect={expect}` to `expect={actual}` "
                f"(or investigate why the number moved if that's unexpected)."
            )
        elif prose_check and "no_prose" not in attrs and not prose_holds(lines, line_no - 1, expect):
            failures.append(
                f"{where}: {label!r} marker says {expect} and that IS the real count, but the "
                f"number {expect} does not appear in the prose around it — the sentence a human "
                f"reads still carries the old value. Fix the prose, or add `no_prose=1` to the "
                f"marker if its sentence deliberately spells no number."
            )
    return failures, checked, deferred


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--roots",
        nargs="*",
        default=DEFAULT_ROOTS,
        help=f"doc files to scan for markers (default: {DEFAULT_ROOTS})",
    )
    parser.add_argument(
        "--vitest-report",
        action="append",
        default=[],
        metavar="PROJECT=PATH",
        help="a vitest JSON report for a `doc-count:vitest` marker's `project`",
    )
    parser.add_argument(
        "--skip-vitest",
        action="store_true",
        help=(
            "defer `doc-count:vitest` markers with no report instead of failing "
            "(prints exactly which ones were deferred; for the toolchain-free doc-counts job)"
        ),
    )
    parser.add_argument(
        "--no-prose-check",
        action="store_true",
        help="only compare the markers, not the prose numbers beside them",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    vitest_reports: dict[str, Path] = {}
    for spec in args.vitest_report:
        project, _, path = spec.partition("=")
        if not project or not path:
            print(f"error: --vitest-report expects PROJECT=PATH, got {spec!r}", file=sys.stderr)
            return 2
        vitest_reports[project] = Path(path)

    all_failures: list[str] = []
    all_deferred: list[str] = []
    checked_markers = 0

    for root in args.roots:
        doc_path = repo_root / root
        if not doc_path.is_file():
            print(f"error: doc file not found: {doc_path}", file=sys.stderr)
            return 2
        failures, checked, deferred = check_doc(
            repo_root, doc_path, vitest_reports, args.skip_vitest, not args.no_prose_check
        )
        all_failures.extend(failures)
        all_deferred.extend(deferred)
        checked_markers += checked

    if checked_markers == 0 and not all_deferred:
        print(
            "error: no `<!-- doc-count:… -->` markers found in "
            f"{args.roots} — if every marker was deliberately removed, remove "
            "this check too rather than let it pass vacuously",
            file=sys.stderr,
        )
        return 2

    if all_deferred:
        print(
            f"doc-count check: {len(all_deferred)} vitest marker(s) deferred to the job that runs "
            "vitest (--skip-vitest):"
        )
        for entry in all_deferred:
            print(f"  - {entry}")

    if all_failures:
        print(f"doc-count check: FAILED — {len(all_failures)} of {checked_markers} marker(s) drifted:\n")
        for failure in all_failures:
            print(f"  - {failure}")
        return 1

    print(f"doc-count check: OK — all {checked_markers} marker(s) in {args.roots} match reality")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
