#!/usr/bin/env python3
"""CI check: the `<!-- doc-count:test ... -->` markers in ROADMAP.md (and any
other doc under `--roots`) still match reality. THE actual fix for the "docs
claim a test count that's been stale for months" class of bug this task was
written to close — every prior fix to one of these numbers rots again the
next time someone adds or removes a test, unless something re-checks it on
every PR. This is that something.

## What a marker looks like

    <!-- doc-count:test sources="crates/sandbox/src" expect=154 label="sandbox unit tests" -->

Placed on its own line, immediately after the prose sentence it backs (see
`ROADMAP.md` for seven live examples). `sources` is a comma-separated list of
paths, each either a directory (walked recursively for `*.rs` files) or a
single `*.rs` file, relative to the repo root. `expect` is the count this
script must reproduce EXACTLY or the check fails, naming the file, the label,
and both numbers so fixing it is a one-line edit.

## Methodology — and its one deliberate limitation

Counts `#[test]` and `#[tokio::test]` attributes via a plain regex over the
file text — NOT `cargo test --list`, which would need a build. This is a
deliberate trade-off: a static count can't run in the same job as `lint`/
`test` without paying for a second full compile, and the whole point of this
check is that it runs on EVERY PR cheaply enough that nobody skips it. It
also means this check cannot see: doc-tests, tests gated behind a
non-default feature the workspace doesn't build with `--all-features`, or a
test generated by a macro that doesn't literally spell `#[test]` in the
source. None of the seven markers this repo ships today hit any of those
cases (verified by cross-checking each against a real `cargo test -p
<crate>` run at the time it was written — see the task report) — if a future
marker's source uses one, prefer fixing the count at its source over
silencing this check.

## Usage

    check_doc_test_counts.py [--roots PATH ...]

Exits 1 and prints every mismatch (not just the first) if any marker's
`expect` no longer matches. Exits 0, printing nothing but a summary, when
every marker holds. Exits 2 on a malformed marker or an unreadable source
path — a broken CHECK is a bug in the marker, not a silent skip.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

MARKER_RE = re.compile(
    r"<!--\s*doc-count:test\s+"
    r'sources="(?P<sources>[^"]+)"\s+'
    r"expect=(?P<expect>\d+)\s+"
    r'label="(?P<label>[^"]*)"\s*-->'
)
TEST_ATTR_RE = re.compile(r"#\[(?:tokio::)?test\]")

DEFAULT_ROOTS = ["ROADMAP.md"]


def count_tests_in_file(path: Path) -> int:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        raise SystemExit(f"error: could not read source {path}: {error}")
    return len(TEST_ATTR_RE.findall(text))


def count_tests_in_source(repo_root: Path, source: str) -> int:
    path = repo_root / source
    if path.is_dir():
        total = 0
        for rs_file in sorted(path.rglob("*.rs")):
            total += count_tests_in_file(rs_file)
        return total
    if path.is_file():
        return count_tests_in_file(path)
    raise SystemExit(f"error: doc-count source does not exist: {source} (resolved {path})")


def check_doc(repo_root: Path, doc_path: Path) -> list[str]:
    """Returns a list of human-readable failure messages (empty = all held)."""
    try:
        text = doc_path.read_text(encoding="utf-8")
    except OSError as error:
        raise SystemExit(f"error: could not read {doc_path}: {error}")

    failures = []
    matches = list(MARKER_RE.finditer(text))
    if not matches:
        return failures

    for match in matches:
        label = match.group("label") or "(unlabeled)"
        expect = int(match.group("expect"))
        sources = [s.strip() for s in match.group("sources").split(",") if s.strip()]
        actual = sum(count_tests_in_source(repo_root, s) for s in sources)
        line_no = text.count("\n", 0, match.start()) + 1
        if actual != expect:
            failures.append(
                f"{doc_path}:{line_no}: {label!r} claims {expect} test(s) over "
                f"{sources}, but {actual} are actually there now. Fix the "
                f"prose AND the marker's `expect={expect}` to `expect={actual}` "
                f"(or investigate why a test appeared/disappeared if that's "
                f"unexpected)."
            )
    return failures


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--roots",
        nargs="*",
        default=DEFAULT_ROOTS,
        help=f"doc files to scan for markers (default: {DEFAULT_ROOTS})",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[2]
    all_failures: list[str] = []
    checked_markers = 0

    for root in args.roots:
        doc_path = repo_root / root
        if not doc_path.is_file():
            print(f"error: doc file not found: {doc_path}", file=sys.stderr)
            return 2
        text = doc_path.read_text(encoding="utf-8")
        checked_markers += len(MARKER_RE.findall(text))
        all_failures.extend(check_doc(repo_root, doc_path))

    if checked_markers == 0:
        print(
            "error: no `<!-- doc-count:test ... -->` markers found in "
            f"{args.roots} — if every marker was deliberately removed, remove "
            "this check too rather than let it pass vacuously",
            file=sys.stderr,
        )
        return 2

    if all_failures:
        print(f"doc-count check: FAILED — {len(all_failures)} of {checked_markers} marker(s) drifted:\n")
        for failure in all_failures:
            print(f"  - {failure}")
        return 1

    print(f"doc-count check: OK — all {checked_markers} marker(s) in {args.roots} match reality")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
