//! `codypendent finetune` — scaffold an Unsloth QLoRA fine-tuning project
//! (`init`), verify the local Python/CUDA setup (`check`), and export the
//! repo's own session/eval history as training data (`dataset export`).
//!
//! Honesty note: this container has no GPU and no Python. `init` only writes
//! text files — it never installs a package or runs Python. `check` shells
//! out read-only to `python3 --version` / `nvidia-smi` (both injectable, so
//! tests mock them with fake scripts rather than depending on real ones) and
//! degrades to actionable guidance when either is missing, exactly as it
//! will in this container. Nothing here claims GPU/device-tested training
//! behavior — the generated `train.py` follows Unsloth's documented QLoRA
//! recipe, but it has not been run by this crate or its tests.
//!
//! `dataset export` is deferred (see [`dataset_export`]'s doc comment for the
//! precise reason) rather than shipped as a fragile, drifting
//! reimplementation of daemon-owned transcript reconstruction.

use std::path::PathBuf;
use std::process::Command;

use anyhow::Context;

use crate::doctor::{Check, Report, Status};

/// The Unsloth repo `finetune init` uses as the training base when
/// `--model` is omitted: a small, popular, pre-quantized-for-QLoRA repo
/// (verified live on the Hugging Face Hub while building this scaffold).
pub const DEFAULT_BASE_MODEL: &str = "unsloth/Qwen3-8B-unsloth-bnb-4bit";

/// The default scaffold directory (repository-relative) when `--out` is
/// omitted.
pub const DEFAULT_OUT_DIR: &str = "finetune";

/// `codypendent finetune init` options.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InitOptions {
    /// The Hugging Face repo `train.py` loads as its base model.
    pub base_model: String,
    /// The directory to scaffold into. Must not already exist (this is a
    /// `cargo new`-style scaffold, not a merge/overwrite).
    pub out_dir: PathBuf,
}

impl Default for InitOptions {
    fn default() -> Self {
        Self {
            base_model: DEFAULT_BASE_MODEL.to_string(),
            out_dir: PathBuf::from(DEFAULT_OUT_DIR),
        }
    }
}

/// What [`init`] wrote, for the CLI to report back.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InitReport {
    pub out_dir: PathBuf,
    pub files_written: Vec<PathBuf>,
}

/// Scaffold an Unsloth QLoRA fine-tuning project at `options.out_dir`:
/// pinned `requirements.txt`, a `train.py` for `options.base_model`, a
/// `dataset/train.jsonl` chat-transcript stub with its own format README,
/// and a top-level `README.md` covering GPU requirements, running the
/// script, GGUF export, and the `ollama create` step. Refuses (no I/O
/// performed) when `out_dir` already exists, so a re-run never silently
/// overwrites an in-progress project.
pub fn init(options: &InitOptions) -> anyhow::Result<InitReport> {
    if options.out_dir.exists() {
        anyhow::bail!(
            "{} already exists — choose a different --out, or remove it first",
            options.out_dir.display()
        );
    }
    let dataset_dir = options.out_dir.join("dataset");
    std::fs::create_dir_all(&dataset_dir)
        .with_context(|| format!("creating {}", dataset_dir.display()))?;

    let files: [(&str, String); 5] = [
        ("requirements.txt", requirements_txt().to_string()),
        ("README.md", readme_md(&options.base_model)),
        ("train.py", train_py(&options.base_model)),
        ("dataset/README.md", dataset_readme_md().to_string()),
        ("dataset/train.jsonl", dataset_train_jsonl().to_string()),
    ];
    let mut files_written = Vec::with_capacity(files.len());
    for (relative, contents) in &files {
        let path = options.out_dir.join(relative);
        std::fs::write(&path, contents).with_context(|| format!("writing {}", path.display()))?;
        files_written.push(path);
    }

    Ok(InitReport {
        out_dir: options.out_dir.clone(),
        files_written,
    })
}

fn requirements_txt() -> &'static str {
    r#####"# Unsloth QLoRA fine-tuning environment, generated by `codypendent
# finetune init`. Requires a CUDA GPU -- see README.md "GPU requirements".
# Nothing in this scaffold has been installed or run in the environment that
# generated it (Codypendent itself needs no GPU and no Python, and never
# executes any of these files).

# Simple install (resolves a prebuilt wheel matching your CUDA + torch):
unsloth
unsloth_zoo
# If that does not resolve for your CUDA/torch combination, use Unsloth's
# installer selector instead and replace the two lines above with the exact
# command it prints for your platform:
#   https://github.com/unslothai/unsloth#installation
torch>=2.5.0
transformers>=4.47.0
trl>=0.13.0
peft>=0.14.0
accelerate>=1.2.0
bitsandbytes>=0.45.0
datasets>=3.2.0
sentencepiece>=0.2.0
huggingface_hub>=0.27.0
"#####
}

const README_TEMPLATE: &str = r#####"# Unsloth QLoRA fine-tune: {{BASE_MODEL}}

Scaffolded by `codypendent finetune init`. This directory is a self-contained
Python project; Codypendent itself never installs or runs any of it -- these
commands are meant to be run by you, on a machine with an NVIDIA GPU.

## GPU requirements

Fine-tuning needs an NVIDIA GPU with CUDA support. 4-bit QLoRA keeps VRAM
requirements far below full fine-tuning, but you still need enough for the
base model's parameter count plus activations -- as a rough guide, budget at
least 8-12 GB of VRAM for a model in the 7-8B parameter range, more for a
larger base. Codypendent has not verified GPU behavior for this scaffold: the
environment that generated it has no GPU and does not install or run Python.
Run `codypendent finetune check` on the machine you intend to train on to
verify Python and CUDA are actually present there.

## Setup

```bash
pip install -r requirements.txt
```

## 1. Prepare your dataset

Edit `dataset/train.jsonl` -- one JSON object per line, each a chat transcript:

```json
{"messages": [{"role": "user", "content": "..."}, {"role": "assistant", "content": "..."}]}
```

See `dataset/README.md` for the exact format `train.py` expects.

## 2. Train

```bash
python train.py
```

This loads `{{BASE_MODEL}}` in 4-bit, attaches a LoRA adapter, and fine-tunes
on your dataset. The adapter is saved to `lora_model/` when training finishes.

## 3. Export to GGUF

Unsloth can merge the LoRA adapter and export straight to GGUF:

```python
from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained("lora_model")
model.save_pretrained_gguf("gguf_model", tokenizer, quantization_method="q4_k_m")
```

This writes a `.gguf` file under `gguf_model/`. Pick a different
`quantization_method` (e.g. `q8_0`, `f16`) to trade size for fidelity.

## 4. Load it into Ollama

Write a `Modelfile` next to the exported GGUF:

```text
FROM ./gguf_model/<the-exported-file>.gguf
```

Then:

```bash
ollama create my-finetuned-model -f Modelfile
```

`my-finetuned-model` now appears in `ollama list`. Add it to Codypendent the
same way as any other local Ollama model: open the `/model` or `/provider`
picker in the TUI against the `ollama` provider, or add a `[[model]]` entry to
`models.toml` by hand with `model = "my-finetuned-model"`. Either way, run
`codypendent models bench <id>` afterward so the router has a measured
profile for it.
"#####;

fn readme_md(base_model: &str) -> String {
    README_TEMPLATE.replace("{{BASE_MODEL}}", base_model)
}

const TRAIN_PY_TEMPLATE: &str = r#####""""Unsloth QLoRA fine-tuning, scaffolded by `codypendent finetune init`.

Base model: {{BASE_MODEL}}

Requires a CUDA GPU (run `codypendent finetune check` to verify). See
README.md for setup, GGUF export, and the `ollama create` step.
"""

from datasets import load_dataset
from trl import SFTConfig, SFTTrainer
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template

MAX_SEQ_LENGTH = 4096
BASE_MODEL = "{{BASE_MODEL}}"
DATASET_PATH = "dataset/train.jsonl"
OUTPUT_DIR = "outputs"
LORA_OUTPUT_DIR = "lora_model"


def load_model():
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=BASE_MODEL,
        max_seq_length=MAX_SEQ_LENGTH,
        load_in_4bit=True,
        dtype=None,  # auto-detect the best dtype for your GPU
    )
    model = FastLanguageModel.get_peft_model(
        model,
        r=16,
        lora_alpha=16,
        lora_dropout=0,
        target_modules=[
            "q_proj",
            "k_proj",
            "v_proj",
            "o_proj",
            "gate_proj",
            "up_proj",
            "down_proj",
        ],
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
    )
    tokenizer = get_chat_template(tokenizer, chat_template="chatml")
    return model, tokenizer


def load_training_dataset(tokenizer):
    dataset = load_dataset("json", data_files=DATASET_PATH, split="train")

    def format_example(example):
        text = tokenizer.apply_chat_template(
            example["messages"], tokenize=False, add_generation_prompt=False
        )
        return {"text": text}

    return dataset.map(format_example)


def main():
    model, tokenizer = load_model()
    dataset = load_training_dataset(tokenizer)

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        args=SFTConfig(
            output_dir=OUTPUT_DIR,
            per_device_train_batch_size=2,
            gradient_accumulation_steps=4,
            warmup_steps=10,
            num_train_epochs=1,
            learning_rate=2e-4,
            logging_steps=1,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=3407,
        ),
    )
    trainer.train()

    model.save_pretrained(LORA_OUTPUT_DIR)
    tokenizer.save_pretrained(LORA_OUTPUT_DIR)
    print(f"LoRA adapter saved to {LORA_OUTPUT_DIR}/")
    print("Next: export a GGUF (see README.md) and `ollama create` it.")


if __name__ == "__main__":
    main()
"#####;

fn train_py(base_model: &str) -> String {
    TRAIN_PY_TEMPLATE.replace("{{BASE_MODEL}}", base_model)
}

fn dataset_readme_md() -> &'static str {
    r#####"# Training dataset

`train.py` reads `train.jsonl` in this directory: one JSON object per line,
each a chat transcript in the same `messages` shape the OpenAI/ChatML APIs
use:

```json
{"messages": [{"role": "user", "content": "..."}, {"role": "assistant", "content": "..."}]}
```

An optional leading `{"role": "system", "content": "..."}` sets the system
prompt for that example. Replace the two stub rows in `train.jsonl` with your
own examples -- more (and more varied) examples generally train better than a
handful of near-duplicates.

`codypendent finetune dataset export` can seed this file from the repo's own
session/eval history where a clean seam exists to do so; run it to see
whether that applies to your setup yet.
"#####
}

fn dataset_train_jsonl() -> &'static str {
    "{\"messages\": [{\"role\": \"system\", \"content\": \"You are a helpful, concise assistant.\"}, {\"role\": \"user\", \"content\": \"What does this function do?\"}, {\"role\": \"assistant\", \"content\": \"Replace this stub example with a real one: a concise, correct answer in the style you want the fine-tuned model to produce.\"}]}\n{\"messages\": [{\"role\": \"user\", \"content\": \"Write a one-line docstring for a function that reverses a string.\"}, {\"role\": \"assistant\", \"content\": \"\\\"\\\"\\\"Return the input string reversed.\\\"\\\"\\\"\"}]}\n"
}

// ---------------------------------------------------------------------------
// `codypendent finetune check`
// ---------------------------------------------------------------------------

/// Verify the local Python + CUDA setup for running the scaffolded
/// `train.py`, read-only. `python_bin`/`nvidia_smi_bin` are injected so
/// tests point them at fake scripts instead of depending on a real
/// interpreter or GPU driver (this container has neither). Mirrors
/// `codypendent doctor`'s `Report`/`Check`/`Status` shape (reused directly,
/// not duplicated) so the two checklists render identically.
#[must_use]
pub fn check(python_bin: &str, nvidia_smi_bin: &str) -> Report {
    let mut report = Report::default();
    check_python(&mut report, python_bin);
    check_cuda(&mut report, nvidia_smi_bin);
    report
}

fn check_python(report: &mut Report, python_bin: &str) {
    let check = match Command::new(python_bin).arg("--version").output() {
        Ok(output) if output.status.success() => {
            let mut version = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if version.is_empty() {
                // Some interpreters print `--version` to stderr.
                version = String::from_utf8_lossy(&output.stderr).trim().to_string();
            }
            Check {
                name: "python".to_string(),
                status: Status::Ok,
                message: version,
                hint: None,
            }
        }
        Ok(output) => Check {
            name: "python".to_string(),
            status: Status::Fail,
            message: format!("`{python_bin} --version` exited with {}", output.status),
            hint: Some(
                "install Python 3.10+ (https://python.org) and ensure it is on PATH".to_string(),
            ),
        },
        Err(_) => Check {
            name: "python".to_string(),
            status: Status::Fail,
            message: format!("`{python_bin}` was not found on PATH"),
            hint: Some(
                "install Python 3.10+ (https://python.org) and ensure it is on PATH".to_string(),
            ),
        },
    };
    report.items.push(check);
}

fn check_cuda(report: &mut Report, nvidia_smi_bin: &str) {
    let check = match Command::new(nvidia_smi_bin)
        .args(["--query-gpu=name,memory.total", "--format=csv,noheader"])
        .output()
    {
        Ok(output) if output.status.success() => {
            let info = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if info.is_empty() {
                Check {
                    name: "cuda".to_string(),
                    status: Status::Warn,
                    message: "nvidia-smi ran but reported no GPU".to_string(),
                    hint: Some(
                        "fine-tuning needs an NVIDIA GPU with CUDA; none detected here".to_string(),
                    ),
                }
            } else {
                Check {
                    name: "cuda".to_string(),
                    status: Status::Ok,
                    message: format!("GPU detected: {info}"),
                    hint: None,
                }
            }
        }
        Ok(output) => Check {
            name: "cuda".to_string(),
            status: Status::Warn,
            message: format!("`{nvidia_smi_bin}` exited with {}", output.status),
            hint: Some("fine-tuning needs an NVIDIA GPU with a working driver".to_string()),
        },
        Err(_) => Check {
            name: "cuda".to_string(),
            status: Status::Warn,
            message: format!("`{nvidia_smi_bin}` was not found on PATH"),
            hint: Some(
                "fine-tuning needs an NVIDIA GPU with CUDA installed; none detected in this \
                 environment"
                    .to_string(),
            ),
        },
    };
    report.items.push(check);
}

// ---------------------------------------------------------------------------
// `codypendent finetune dataset export` (deferred)
// ---------------------------------------------------------------------------

/// `codypendent finetune dataset export`: seed `dataset/train.jsonl` from the
/// repo's own session/eval history — DEFERRED, not stubbed-silent. Returns
/// the explanation (the CLI prints it and exits 0; nothing failed, the
/// feature is honestly incomplete).
///
/// Why no clean seam exists today, checked before writing this scaffold:
///
/// - **Session transcripts.** The daemon's own turn-reconstruction
///   (`session_transcript`/`continuation_prior` in
///   `crates/codypendentd/src/session_history.rs`) is `pub(crate)`-only
///   inside `codypendentd` — unreachable from `codypendent-cli` even though
///   `cli` depends on that crate (Rust visibility is not relaxed by a Cargo
///   dependency edge). No protocol `Command` exposes a reconstructed
///   transcript to a client either — only raw `SessionEvent`s via
///   `codypendent attach --events jsonl`, which would mean re-deriving that
///   same reconstruction here (streamed-delta coalescing, tool-result
///   summarizing, run compaction, …) as a second, drifting implementation of
///   daemon-owned logic — exactly the kind of duplicated-and-diverging code
///   path this project's own review process flags elsewhere.
/// - **Eval reports.** `codypendent-eval`'s `SuiteReport`/`CaseResult`/
///   `RunObservation` (`crates/eval/src/case.rs`) carry only structured
///   pass/fail/cost/duration signals — no raw model completion text — so
///   today's eval JSONL has no assistant-turn text to export either.
///
/// The clean fix is a protocol-level read command (e.g.
/// `ReadSessionTranscript`) backed by a small `pub` wrapper around the
/// existing `pub(crate)` reconstruction, so a client gets the SAME
/// transcript a continuation run already seeds itself with. That is a
/// daemon/protocol change — out of this vertical's ownership — so it is
/// filed as a follow-up rather than built here.
#[must_use]
pub fn dataset_export() -> String {
    "codypendent finetune dataset export: deferred.\n\n\
     No clean read-only seam exists yet for the CLI to export a reconstructed \
     chat transcript as fine-tuning data:\n\n\
     - Session transcripts: the daemon's own turn-reconstruction logic \
     (`session_transcript`/`continuation_prior` in \
     crates/codypendentd/src/session_history.rs) is `pub(crate)`-only inside \
     codypendentd, and no protocol Command exposes a reconstructed transcript \
     to a client -- only raw SessionEvents via `codypendent attach --events \
     jsonl`, which would mean re-deriving that same reconstruction here as a \
     second, drifting implementation of daemon-owned logic.\n\
     - Eval reports: codypendent-eval's SuiteReport/CaseResult/RunObservation \
     (crates/eval/src/case.rs) carry only structured pass/fail/cost/duration \
     signals -- no raw model completion text -- so today's eval JSONL has no \
     assistant-turn text to export either.\n\n\
     The clean fix is a protocol-level read command (e.g. ReadSessionTranscript) \
     backed by a small `pub` wrapper around the existing reconstruction -- a \
     daemon/protocol change, filed as a follow-up rather than built here.\n\n\
     In the meantime: hand-write examples into dataset/train.jsonl (see \
     dataset/README.md for the exact shape)."
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    // ------------------------------------------------------------------
    // init — golden-file tests
    // ------------------------------------------------------------------

    const GOLDEN_REQUIREMENTS_TXT: &str = r#####"# Unsloth QLoRA fine-tuning environment, generated by `codypendent
# finetune init`. Requires a CUDA GPU -- see README.md "GPU requirements".
# Nothing in this scaffold has been installed or run in the environment that
# generated it (Codypendent itself needs no GPU and no Python, and never
# executes any of these files).

# Simple install (resolves a prebuilt wheel matching your CUDA + torch):
unsloth
unsloth_zoo
# If that does not resolve for your CUDA/torch combination, use Unsloth's
# installer selector instead and replace the two lines above with the exact
# command it prints for your platform:
#   https://github.com/unslothai/unsloth#installation
torch>=2.5.0
transformers>=4.47.0
trl>=0.13.0
peft>=0.14.0
accelerate>=1.2.0
bitsandbytes>=0.45.0
datasets>=3.2.0
sentencepiece>=0.2.0
huggingface_hub>=0.27.0
"#####;

    #[test]
    fn requirements_txt_matches_the_golden_file() {
        assert_eq!(requirements_txt(), GOLDEN_REQUIREMENTS_TXT);
    }

    #[test]
    fn readme_substitutes_the_base_model_everywhere_it_appears() {
        let readme = readme_md("unsloth/Qwen3-8B-unsloth-bnb-4bit");
        assert!(readme.contains("# Unsloth QLoRA fine-tune: unsloth/Qwen3-8B-unsloth-bnb-4bit"));
        assert!(readme.contains("loads `unsloth/Qwen3-8B-unsloth-bnb-4bit` in 4-bit"));
        assert!(
            !readme.contains("{{BASE_MODEL}}"),
            "every template token must be substituted:\n{readme}"
        );
        // The doc-required steps are all present.
        assert!(readme.contains("GPU requirements"));
        assert!(readme.contains("pip install -r requirements.txt"));
        assert!(readme.contains("python train.py"));
        assert!(readme.contains("save_pretrained_gguf"));
        assert!(readme.contains("ollama create"));
        assert!(readme.contains("codypendent models bench"));
    }

    #[test]
    fn readme_substitution_works_for_a_different_base_model() {
        let readme = readme_md("someorg/some-other-base-4bit");
        assert!(readme.contains("someorg/some-other-base-4bit"));
        assert!(!readme.contains("unsloth/Qwen3-8B-unsloth-bnb-4bit"));
    }

    #[test]
    fn train_py_substitutes_the_base_model_and_stays_valid_looking_python() {
        let script = train_py("unsloth/Qwen3-8B-unsloth-bnb-4bit");
        assert!(script.contains(r#"BASE_MODEL = "unsloth/Qwen3-8B-unsloth-bnb-4bit""#));
        assert!(!script.contains("{{BASE_MODEL}}"));
        assert!(script.contains("from unsloth import FastLanguageModel"));
        assert!(script.contains("FastLanguageModel.get_peft_model"));
        assert!(script.contains("SFTTrainer("));
        assert!(script.contains("if __name__ == \"__main__\":"));
        // Every opened paren/bracket/brace balances (a cheap syntax sanity
        // check without a real Python parser).
        assert_balanced(&script, '(', ')');
        assert_balanced(&script, '[', ']');
    }

    fn assert_balanced(text: &str, open: char, close: char) {
        let opens = text.chars().filter(|&c| c == open).count();
        let closes = text.chars().filter(|&c| c == close).count();
        assert_eq!(
            opens, closes,
            "unbalanced {open}{close} in generated script"
        );
    }

    #[test]
    fn dataset_readme_documents_the_messages_shape() {
        let readme = dataset_readme_md();
        assert!(readme.contains("\"messages\""));
        assert!(readme.contains("\"role\""));
    }

    #[test]
    fn dataset_train_jsonl_is_two_valid_json_lines_shaped_as_chat_transcripts() {
        let jsonl = dataset_train_jsonl();
        let lines: Vec<&str> = jsonl.lines().collect();
        assert_eq!(lines.len(), 2);
        for line in lines {
            let value: serde_json::Value =
                serde_json::from_str(line).expect("each line is valid JSON");
            let messages = value["messages"].as_array().expect("a messages array");
            assert!(!messages.is_empty());
            for message in messages {
                assert!(message["role"].is_string());
                assert!(message["content"].is_string());
            }
        }
    }

    #[test]
    fn init_writes_every_scaffolded_file_with_the_expected_content() {
        let temp = tempfile::tempdir().expect("tempdir");
        let out_dir = temp.path().join("my-finetune");
        let options = InitOptions {
            base_model: "unsloth/Qwen3-8B-unsloth-bnb-4bit".to_string(),
            out_dir: out_dir.clone(),
        };
        let report = init(&options).expect("init succeeds");
        assert_eq!(report.out_dir, out_dir);
        assert_eq!(report.files_written.len(), 5);

        assert_eq!(
            std::fs::read_to_string(out_dir.join("requirements.txt")).unwrap(),
            GOLDEN_REQUIREMENTS_TXT
        );
        assert_eq!(
            std::fs::read_to_string(out_dir.join("README.md")).unwrap(),
            readme_md(&options.base_model)
        );
        assert_eq!(
            std::fs::read_to_string(out_dir.join("train.py")).unwrap(),
            train_py(&options.base_model)
        );
        assert_eq!(
            std::fs::read_to_string(out_dir.join("dataset/README.md")).unwrap(),
            dataset_readme_md()
        );
        assert_eq!(
            std::fs::read_to_string(out_dir.join("dataset/train.jsonl")).unwrap(),
            dataset_train_jsonl()
        );
    }

    #[test]
    fn init_refuses_to_overwrite_an_existing_directory() {
        let temp = tempfile::tempdir().expect("tempdir");
        let out_dir = temp.path().join("already-here");
        std::fs::create_dir_all(&out_dir).unwrap();
        let options = InitOptions {
            base_model: DEFAULT_BASE_MODEL.to_string(),
            out_dir: out_dir.clone(),
        };
        let error = init(&options).expect_err("must refuse an existing directory");
        assert!(error.to_string().contains(&out_dir.display().to_string()));
        // Nothing was written into it.
        assert_eq!(std::fs::read_dir(&out_dir).unwrap().count(), 0);
    }

    #[test]
    fn default_init_options_use_the_documented_defaults() {
        let options = InitOptions::default();
        assert_eq!(options.base_model, DEFAULT_BASE_MODEL);
        assert_eq!(options.out_dir, PathBuf::from(DEFAULT_OUT_DIR));
    }

    // ------------------------------------------------------------------
    // check — fake python3/nvidia-smi (no real GPU or interpreter here)
    // ------------------------------------------------------------------

    fn fake_script(dir: &std::path::Path, name: &str, body: &str) -> std::path::PathBuf {
        let path = dir.join(name);
        std::fs::write(&path, body).expect("write fake script");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755))
                .expect("chmod fake script");
        }
        path
    }

    #[test]
    fn check_reports_ok_when_python_and_cuda_are_both_present() {
        let dir = tempfile::tempdir().expect("tempdir");
        let python = fake_script(
            dir.path(),
            "python3",
            "#!/bin/sh\necho 'Python 3.12.4'\nexit 0\n",
        );
        let nvidia_smi = fake_script(
            dir.path(),
            "nvidia-smi",
            "#!/bin/sh\necho 'NVIDIA GeForce RTX 4090, 24564 MiB'\nexit 0\n",
        );
        let report = check(
            python.to_str().expect("utf8 path"),
            nvidia_smi.to_str().expect("utf8 path"),
        );
        assert_eq!(report.worst(), Status::Ok);
        let python_check = report.items.iter().find(|c| c.name == "python").unwrap();
        assert_eq!(python_check.status, Status::Ok);
        assert!(python_check.message.contains("3.12.4"));
        let cuda_check = report.items.iter().find(|c| c.name == "cuda").unwrap();
        assert_eq!(cuda_check.status, Status::Ok);
        assert!(cuda_check.message.contains("RTX 4090"));
    }

    #[test]
    fn check_fails_closed_with_actionable_guidance_when_python_is_missing() {
        let dir = tempfile::tempdir().expect("tempdir");
        let nvidia_smi = fake_script(dir.path(), "nvidia-smi", "#!/bin/sh\nexit 0\n");
        let report = check(
            "codypendent-test-definitely-not-a-real-python",
            nvidia_smi.to_str().expect("utf8 path"),
        );
        let python_check = report.items.iter().find(|c| c.name == "python").unwrap();
        assert_eq!(python_check.status, Status::Fail);
        assert!(python_check.hint.as_deref().unwrap().contains("python.org"));
        assert_eq!(report.worst(), Status::Fail);
    }

    #[test]
    fn check_warns_not_fails_when_no_gpu_is_present() {
        // This is the honest, real state of the container that built this
        // scaffold: no GPU, no `nvidia-smi`. A missing GPU degrades the
        // report to a warning (fine-tuning needs a GPU, but the scaffold
        // itself — dataset editing, dry inspection — doesn't) rather than a
        // hard failure.
        let dir = tempfile::tempdir().expect("tempdir");
        let python = fake_script(
            dir.path(),
            "python3",
            "#!/bin/sh\necho 'Python 3.12.4'\nexit 0\n",
        );
        let report = check(
            python.to_str().expect("utf8 path"),
            "codypendent-test-definitely-not-a-real-nvidia-smi",
        );
        let cuda_check = report.items.iter().find(|c| c.name == "cuda").unwrap();
        assert_eq!(cuda_check.status, Status::Warn);
        assert!(cuda_check.message.contains("not found"));
        assert!(cuda_check
            .hint
            .as_deref()
            .unwrap()
            .to_lowercase()
            .contains("gpu"));
        assert_eq!(
            report.worst(),
            Status::Warn,
            "no GPU must warn, not fail, when python itself is fine"
        );
    }

    #[test]
    fn check_never_claims_a_gpu_is_present_when_nvidia_smi_reports_none() {
        let dir = tempfile::tempdir().expect("tempdir");
        let python = fake_script(
            dir.path(),
            "python3",
            "#!/bin/sh\necho 'Python 3.12.4'\nexit 0\n",
        );
        // nvidia-smi exists and exits 0 but prints nothing (a real shape:
        // the driver loaded but no device is attached).
        let nvidia_smi = fake_script(dir.path(), "nvidia-smi", "#!/bin/sh\nexit 0\n");
        let report = check(
            python.to_str().expect("utf8 path"),
            nvidia_smi.to_str().expect("utf8 path"),
        );
        let cuda_check = report.items.iter().find(|c| c.name == "cuda").unwrap();
        assert_eq!(cuda_check.status, Status::Warn);
        assert!(!cuda_check.message.to_lowercase().contains("detected: "));
    }

    // ------------------------------------------------------------------
    // dataset export — deferred, not silently stubbed
    // ------------------------------------------------------------------

    #[test]
    fn dataset_export_explains_the_precise_deferral_reason() {
        let message = dataset_export();
        assert!(message.contains("deferred"));
        // Names the exact blocking symbols/files, not a vague "not implemented".
        assert!(message.contains("session_history.rs"));
        assert!(message.contains("pub(crate)"));
        assert!(message.contains("SuiteReport"));
        assert!(message.contains("dataset/train.jsonl"));
    }
}
