//! The code-graph fold: what one file costs, and therefore what one repository
//! scan costs.
//!
//! # Why this function
//!
//! `measure_file_graph` is the scan's per-file preflight — it parses a file with
//! tree-sitter and reports how many nodes and edges folding it WOULD write, so
//! the scan can spend a bounded node budget on the heaviest files rather than
//! discovering the weight after the fact. It is called once per candidate file
//! on every scan, which makes it the one function whose cost is multiplied by
//! the size of the repository.
//!
//! Its doc comment says it "costs nothing extra where it is used", which is a
//! claim about the SCAN's structure (the preflight parse is reused, not
//! repeated) and NOT a claim that the parse itself is cheap. This bench
//! measures the parse, so the second reading of that sentence can never be
//! assumed: multiply the per-file number by the file count to get the floor on
//! `Preparing`.
//!
//! # The pathological case is the point
//!
//! The scan bug that motivated this harness was a graph that reached 510,904
//! nodes, and the mechanism named in `measure_file_graph`'s own doc comment is
//! that one machine-generated FFI binding module folds to five figures of
//! symbols by itself. A corpus of tidy hand-written files would therefore
//! measure the case that was never the problem, so `generated_bindings` below
//! reproduces the shape that was: thousands of flat declarations in one file.
//!
//! # Determinism
//!
//! Every source file is generated in-process from an index — no repository is
//! read, no filesystem is touched, no clock, no network, no global state.
//! `RepositoryId` is a fixed UUID rather than `stable_repository_id` of a real
//! path, so the numbers do not depend on where this checkout lives.

use codypendent_knowledge::codegraph::{measure_file_graph, parse_symbols};
use codypendent_protocol::RepositoryId;
use criterion::{criterion_group, criterion_main, Criterion, Throughput};
use std::hint::black_box;

fn repo() -> RepositoryId {
    RepositoryId(uuid::Uuid::from_u128(
        0x9a9a_0000_0000_0000_0000_0000_0000_0001,
    ))
}

/// A hand-written-looking Rust module: a struct, an impl block, some free
/// functions with bodies that call each other, and doc comments. `items`
/// controls the size; 40 is roughly a 400-line source file.
fn rust_module(items: usize) -> String {
    let mut s = String::from("use std::collections::HashMap;\n\n");
    for i in 0..items {
        s.push_str(&format!(
            "/// Folds record {i} into the projection.\n\
             #[derive(Debug, Clone, PartialEq)]\n\
             pub struct Record{i} {{\n\
             \x20   pub id: u64,\n\
             \x20   pub label: String,\n\
             \x20   pub weights: HashMap<String, f64>,\n\
             }}\n\n\
             impl Record{i} {{\n\
             \x20   pub fn new(id: u64, label: String) -> Self {{\n\
             \x20       Self {{ id, label, weights: HashMap::new() }}\n\
             \x20   }}\n\n\
             \x20   pub fn weight(&self, key: &str) -> Option<f64> {{\n\
             \x20       self.weights.get(key).copied()\n\
             \x20   }}\n\
             }}\n\n\
             pub fn fold_record_{i}(input: &Record{i}) -> u64 {{\n\
             \x20   let base = input.id.wrapping_mul(31);\n\
             \x20   base ^ input.label.len() as u64\n\
             }}\n\n"
        ));
    }
    s
}

/// The shape that broke the scan: a machine-generated bindings module — a flat
/// wall of `extern` declarations and constants with no nesting and no bodies.
/// One of these outweighs hundreds of hand-written files.
fn generated_bindings(decls: usize) -> String {
    let mut s =
        String::from("// @generated by bindgen. Do not edit.\n#![allow(non_snake_case)]\n\n");
    for i in 0..decls {
        s.push_str(&format!(
            "pub const FLAG_CONSTANT_{i}: u32 = {i}u32;\n\
             extern \"system\" {{\n\
             \x20   pub fn NativeCall{i}(handle: isize, flags: u32, out: *mut u8) -> i32;\n\
             }}\n"
        ));
    }
    s
}

fn python_module(items: usize) -> String {
    let mut s = String::from("import dataclasses\nfrom typing import Optional\n\n");
    for i in 0..items {
        s.push_str(&format!(
            "@dataclasses.dataclass\n\
             class Record{i}:\n\
             \x20   id: int\n\
             \x20   label: str\n\n\
             \x20   def weight(self, key: str) -> Optional[float]:\n\
             \x20       return self.weights.get(key)\n\n\
             def fold_record_{i}(record: Record{i}) -> int:\n\
             \x20   return (record.id * 31) ^ len(record.label)\n\n"
        ));
    }
    s
}

fn typescript_module(items: usize) -> String {
    let mut s = String::from("import { EventEmitter } from 'node:events';\n\n");
    for i in 0..items {
        s.push_str(&format!(
            "export interface Record{i} {{\n\
             \x20 id: number;\n\
             \x20 label: string;\n\
             }}\n\n\
             export class Folder{i} extends EventEmitter {{\n\
             \x20 constructor(private readonly seed: number) {{ super(); }}\n\
             \x20 fold(record: Record{i}): number {{\n\
             \x20   return (record.id * 31) ^ record.label.length ^ this.seed;\n\
             \x20 }}\n\
             }}\n\n\
             export function foldRecord{i}(record: Record{i}): number {{\n\
             \x20 return new Folder{i}({i}).fold(record);\n\
             }}\n\n"
        ));
    }
    s
}

fn bench_fold_one_file(c: &mut Criterion) {
    let repository = repo();
    let mut group = c.benchmark_group("codegraph/measure_file");

    let cases: Vec<(&str, String)> = vec![
        ("rust/small.rs", rust_module(4)),
        ("rust/typical.rs", rust_module(40)),
        ("rust/large.rs", rust_module(200)),
        ("rust/generated.rs", generated_bindings(2_000)),
        ("python/typical.py", python_module(40)),
        ("typescript/typical.ts", typescript_module(40)),
    ];

    for (path, source) in &cases {
        // Bytes/sec is the comparable unit across languages: a grammar that is
        // twice as slow per byte shows up as half the throughput regardless of
        // how verbose the generated fixture happens to be.
        group.throughput(Throughput::Bytes(source.len() as u64));
        group.bench_function(*path, |b| {
            b.iter(|| {
                measure_file_graph(black_box(repository), black_box(path), black_box(source))
                    .expect("fold")
            })
        });
    }

    group.finish();
}

/// The adapter-facing pure parse. Same tree-sitter walk, but it keeps only the
/// owned symbols — so the gap between this and `measure_file` is what the edge
/// bookkeeping costs, not what the parse costs.
fn bench_parse_symbols(c: &mut Criterion) {
    let mut group = c.benchmark_group("codegraph/parse_symbols");
    let source = rust_module(40);
    group.throughput(Throughput::Bytes(source.len() as u64));
    group.bench_function("rust/typical.rs", |b| {
        b.iter(|| parse_symbols(black_box("rust/typical.rs"), black_box(&source)).expect("parse"))
    });
    group.finish();
}

/// A whole-repository preflight: the per-file number above, multiplied by a
/// realistic file count and mix. This is the number that shows up to an
/// operator as time spent in `Preparing`, and it is the reason a file-count cap
/// alone cannot bound the scan — one generated file in the mix moves it.
fn bench_repository_scan(c: &mut Criterion) {
    let repository = repo();
    let mut group = c.benchmark_group("codegraph/repository_preflight");
    // Fewer samples: each iteration folds an entire synthetic repository, so the
    // default 100 would run for minutes without telling us anything the smaller
    // sample does not.
    group.sample_size(10);

    for files in [500usize, 2_000] {
        let corpus: Vec<(String, String)> = (0..files)
            .map(|i| match i % 5 {
                0 => (format!("src/mod{i}.py"), python_module(8 + i % 20)),
                1 => (format!("src/mod{i}.ts"), typescript_module(8 + i % 20)),
                _ => (format!("src/mod{i}.rs"), rust_module(8 + i % 20)),
            })
            .collect();
        let bytes: usize = corpus.iter().map(|(_, s)| s.len()).sum();
        group.throughput(Throughput::Bytes(bytes as u64));

        group.bench_function(format!("{files}_files"), |b| {
            b.iter(|| {
                let mut nodes = 0usize;
                for (path, source) in black_box(&corpus) {
                    nodes += measure_file_graph(repository, path, source)
                        .expect("fold")
                        .nodes;
                }
                nodes
            })
        });
    }

    group.finish();
}

criterion_group!(
    benches,
    bench_fold_one_file,
    bench_parse_symbols,
    bench_repository_scan
);
criterion_main!(benches);
